// Populating the 'constants.ts' file with application constants.
import { Subject, Language, Difficulty } from './types';

export const EXAM_SUBJECTS: Subject[] = [
  Subject.Physics,
  Subject.Chemistry,
  Subject.Math,
  Subject.English,
];

export const EXAM_DIFFICULTIES: Difficulty[] = [
  Difficulty.Easy,
  Difficulty.Medium,
  Difficulty.Hard,
  Difficulty.Mixed,
];

export const EXAM_TOPICS: Record<Subject, Record<string, { en: string; bn: string }>> = {
  [Subject.Physics]: {
    'vectors': { en: 'Vectors', bn: 'ভেক্টর' },
    'dynamics': { en: 'Dynamics & Newtonian Mechanics', bn: 'গতিবিদ্যা ও নিউটোনিয়ান বলবিদ্যা' },
    'work_energy': { en: 'Work, Energy & Power', bn: 'কাজ, শক্তি ও ক্ষমতা' },
    'gravitation': { en: 'Gravitation & Properties of Matter', bn: 'মহাকর্ষ ও পদার্থের বৈশিষ্ট্য' },
    'motion_waves': { en: 'Periodic Motion & Waves', bn: 'পর্যাবৃত্ত গতি ও তরঙ্গ' },
    'thermodynamics': { en: 'Thermodynamics', bn: 'তাপগতিবিদ্যা' },
    'electricity': { en: 'Current & Static Electricity', bn: 'চল ও স্থির তড়িৎ' },
    'magnetism': { en: 'Magnetism & EMI', bn: 'চৌম্বকত্ব ও তড়িৎচুম্বকীয় আবেশ' },
    'optics': { en: 'Geometrical & Physical Optics', bn: 'জ্যামিতিক ও ভৌত আলোকবিজ্ঞান' },
    'modern_physics': { en: 'Modern Physics & Electronics', bn: 'আধুনিক পদার্থবিজ্ঞান ও ইলেকট্রনিক্স' },
  },
  [Subject.Chemistry]: {
    'qualitative': { en: 'Qualitative Chemistry', bn: 'গুণগত রসায়ন' },
    'periodic_properties': { en: 'Periodic Properties & Bonding', bn: 'পর্যায়বৃত্ত ধর্ম ও বন্ধন' },
    'kinetics_equilibrium': { en: 'Chemical Kinetics & Equilibrium', bn: 'রাসায়নিক গতিবিদ্যা ও সাম্যাবস্থা' },
    'electrochemistry': { en: 'Electrochemistry', bn: 'তড়িৎ রসায়ন' },
    'environmental': { en: 'Environmental Chemistry', bn: 'পরিবেশ রসায়ন' },
    'aliphatics': { en: 'Organic Chemistry - Aliphatics', bn: 'জৈব রসায়ন - অ্যালিফ্যাটিক' },
    'aromatics_polymers': { en: 'Organic Chemistry - Aromatics & Polymers', bn: 'জৈব রসায়ন - অ্যারোমেটিক ও পলিমার' },
    'quantitative': { en: 'Quantitative Chemistry (Stoichiometry)', bn: 'পরিমাণগত রসায়ন (স্টয়কিওমেট্রি)' },
  },
  [Subject.Math]: {
    'matrices_determinants': { en: 'Matrices & Determinants', bn: 'ম্যাট্রিক্স ও নির্ণায়ক' },
    'vectors_3d': { en: 'Vectors & 3D Geometry', bn: 'ভেক্টর ও ত্রি-মাত্রিক জ্যামিতি' },
    'lines_circles': { en: 'Straight Lines & Circles', bn: 'সরলরেখা ও বৃত্ত' },
    'pnc_probability': { en: 'Permutations, Combinations & Probability', bn: 'বিন্যাস, সমাবেশ ও সম্ভাব্যতা' },
    'trigonometry': { en: 'Trigonometry', bn: 'ত্রিকোণমিতি' },
    'diff_calculus': { en: 'Differential Calculus', bn: 'অন্তরীকরণ' },
    'int_calculus': { en: 'Integral Calculus', bn: 'যোগজীকরণ' },
    'mechanics': { en: 'Dynamics & Statics', bn: 'গতিবিদ্যা ও স্থিতিবিদ্যা' },
  },
  [Subject.English]: {
    'grammar': { en: 'Grammar (Tense, Voice, Parts of Speech)', bn: 'ব্যাকরণ (কাল, বাচ্য, পদ)' },
    'vocabulary': { en: 'Vocabulary (Synonym, Antonym, Analogy)', bn: 'শব্দভান্ডার (সমার্থক, বিপরীতার্থক, সাদৃশ্য)' },
    'sentence_structure': { en: 'Sentence Structure & Correction', bn: 'বাক্য গঠন ও শুদ্ধি' },
    'comprehension': { en: 'Reading Comprehension', bn: 'পাঠ বোধগম্যতা' },
    'idioms_phrases': { en: 'Idioms & Phrases', bn: 'প্রবাদ ও বাক্যাংশ' },
  },
  // FullMock is not a selectable subject with topics, so it's omitted here.
  [Subject.FullMock]: {},
};


export const TOTAL_QUESTIONS = 20;
export const EXAM_DURATION_SECONDS = 720; // 20 questions * 36 seconds

export const FULL_MOCK_PHYSICS_QUESTIONS = 33;
export const FULL_MOCK_CHEMISTRY_QUESTIONS = 33;
export const FULL_MOCK_MATH_QUESTIONS = 34;
export const FULL_MOCK_ENGLISH_QUESTIONS = 20;
export const FULL_MOCK_TOTAL_QUESTIONS = FULL_MOCK_PHYSICS_QUESTIONS + FULL_MOCK_CHEMISTRY_QUESTIONS + FULL_MOCK_MATH_QUESTIONS + FULL_MOCK_ENGLISH_QUESTIONS;
export const FULL_MOCK_DURATION_SECONDS = 4320; // 72 minutes

export const NEGATIVE_MARKING_PER_WRONG_ANSWER = 0.25;

export const LOCALIZATIONS = {
  [Language.English]: {
    homeTitle: 'AI-Powered Exam Preparation',
    homeSubtitle: 'Select a subject, difficulty, or start a full mock test.',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    mixed: 'Mixed',
    topic: 'Chapters',
    allTopics: 'All Chapters',
    selectTopics: 'Select Chapters',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    chaptersSelected: 'chapters selected',
    footerText: 'Powered by Gemini AI',
    startExam: 'Start Exam',
    submit: 'Submit',
    next: 'Next',
    previous: 'Previous',
    skip: 'Skip',
    question: 'Question',
    of: 'of',
    score: 'Score',
    yourAnswer: 'Your Answer',
    correctAnswer: 'Correct Answer',
    explanation: 'Explanation',
    backToHome: 'Back to Home',
    resultsTitle: 'Exam Results',
    timeTaken: 'Time Taken',
    timeLeft: 'Time Left',
    seconds: 'seconds',
    accuracy: 'Accuracy',
    incorrectAnswers: 'Incorrect Answers',
    noIncorrectAnswers: 'Great job! No incorrect answers.',
    generatingQuestions: 'Generating your exam questions with AI...',
    generatingFullMock: 'Generating your full mock test... This may take a moment.',
    generatingQuestions1: 'Warming up the AI professor...',
    generatingQuestions2: 'Crafting challenging analytical problems...',
    generatingQuestions3: 'Calibrating difficulty levels...',
    generatingQuestions4: 'Finalizing the question set. Good luck!',
    analyzingResults: 'Analyzing your results...',
    correct: 'Correct',
    wrong: 'Wrong',
    skipped: 'Skipped',
    allQuestions: 'All Questions',
    questionOverview: 'Question Overview',
    retry: 'Retry',
    errorApi: 'API Key Issue',
    errorNetwork: 'Network Error',
    errorResponse: 'Invalid Response',
    errorGeneric: 'Generation Failed',
    errorApiMessage: 'There seems to be an issue with the API key. Please contact the administrator.',
    errorNetworkMessage: 'A network error occurred. Please check your internet connection and try again.',
    errorResponseMessage: 'The AI returned a response that could not be understood. This might be a temporary issue.',
    errorGenericMessage: 'An unexpected error occurred while generating questions. Please try again.',
    skippedQuestionsTitle: 'Skipped Questions',
    unanswered: 'Unanswered',
    answered: 'Answered',
    current: 'Current',
    progress: 'Progress',
    fullMockTitle: 'Full Mock Test',
    fullMockDescription: 'A 120-question exam covering Physics, Chemistry, Math, and English.',
    fullMockTime: '72 Minutes',
    startMockTest: 'Start Mock Test',
  },
  [Language.Bengali]: {
    homeTitle: 'এআই-চালিত পরীক্ষার প্রস্তুতি',
    homeSubtitle: 'একটি বিষয়, অসুবিধা নির্বাচন করুন বা একটি সম্পূর্ণ মক টেস্ট শুরু করুন।',
    easy: 'সহজ',
    medium: 'মাঝারি',
    hard: 'কঠিন',
    mixed: 'মিশ্র',
    topic: 'অধ্যায়',
    allTopics: 'সব অধ্যায়',
    selectTopics: 'অধ্যায় নির্বাচন করুন',
    selectAll: 'সব নির্বাচন করুন',
    deselectAll: 'সব বাতিল করুন',
    chaptersSelected: 'টি অধ্যায় নির্বাচিত',
    footerText: 'Gemini AI দ্বারা চালিত',
    startExam: 'পরীক্ষা শুরু করুন',
    submit: 'জমা দিন',
    next: 'পরবর্তী',
    previous: 'পূর্ববর্তী',
    skip: 'এড়িয়ে যান',
    question: 'প্রশ্ন',
    of: 'এর মধ্যে',
    score: 'স্কোর',
    yourAnswer: 'আপনার উত্তর',
    correctAnswer: 'সঠিক উত্তর',
    explanation: 'ব্যাখ্যা',
    backToHome: 'হোমে ফিরে যান',
    resultsTitle: 'পরীক্ষার ফলাফল',
    timeTaken: 'সময় লেগেছে',
    timeLeft: 'বাকি সময়',
    seconds: 'সেকেন্ড',
    accuracy: 'সঠিকতা',
    incorrectAnswers: 'ভুল উত্তর',
    noIncorrectAnswers: 'দারুণ! কোনো ভুল উত্তর নেই।',
    generatingQuestions: 'AI দিয়ে আপনার পরীক্ষার প্রশ্ন তৈরি করা হচ্ছে...',
    generatingFullMock: 'আপনার সম্পূর্ণ মক পরীক্ষা তৈরি করা হচ্ছে... এটি কিছু সময় নিতে পারে।',
    generatingQuestions1: 'এআই অধ্যাপককে প্রস্তুত করা হচ্ছে...',
    generatingQuestions2: 'জটিল বিশ্লেষণাত্মক সমস্যা তৈরি করা হচ্ছে...',
    generatingQuestions3: 'কঠিনতার স্তর ক্যালিব্রেট করা হচ্ছে...',
    generatingQuestions4: 'প্রশ্ন সেট চূড়ান্ত করা হচ্ছে। শুভকামনা!',
    analyzingResults: 'আপনার ফলাফল বিশ্লেষণ করা হচ্ছে...',
    correct: 'সঠিক',
    wrong: 'ভুল',
    skipped: 'এড়িয়ে গেছেন',
    allQuestions: 'সব প্রশ্ন',
    questionOverview: 'প্রশ্ন ওভারভিউ',
    retry: 'আবার চেষ্টা করুন',
    errorApi: 'API কী সমস্যা',
    errorNetwork: 'নেটওয়ার্ক ত্রুটি',
    errorResponse: 'অবৈধ প্রতিক্রিয়া',
    errorGeneric: 'প্রশ্ন তৈরি ব্যর্থ হয়েছে',
    errorApiMessage: 'API কী নিয়ে একটি সমস্যা হয়েছে। অনুগ্রহ করে প্রশাসকের সাথে যোগাযোগ করুন।',
    errorNetworkMessage: 'একটি নেটওয়ার্ক ত্রুটি ঘটেছে। অনুগ্রহ করে আপনার ইন্টারনেট সংযোগ পরীক্ষা করে আবার চেষ্টা করুন।',
    errorResponseMessage: 'AI একটি প্রতিক্রিয়া ফেরত দিয়েছে যা বোঝা যায়নি। এটি একটি অস্থায়ী সমস্যা হতে পারে।',
    errorGenericMessage: 'প্রশ্ন তৈরি করার সময় একটি অপ্রত্যাশিত ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    skippedQuestionsTitle: 'এড়িয়ে যাওয়া প্রশ্ন',
    unanswered: 'উত্তরহীন',
    answered: 'উত্তর দিয়েছেন',
    current: 'বর্তমান',
    progress: 'অগ্রগতি',
    fullMockTitle: 'সম্পূর্ণ মক টেস্ট',
    fullMockDescription: 'পদার্থবিজ্ঞান, রসায়ন, গণিত এবং ইংরেজি কভার করে ১২০টি প্রশ্নের পরীক্ষা।',
    fullMockTime: '৭২ মিনিট',
    startMockTest: 'মক টেস্ট শুরু করুন',
  },
};